[project]
name = "clovers-client"
version = "0.0.2"
description = ""
authors = [{ name = "KarisAya", email = "karisaya@foxmail.com" }]
readme = "README.md"
requires-python = ">=3.12,<4.0.0"

dependencies = ["pydantic (>=2.10.6,<3.0.0)", "clovers (>=0.4.5,<0.5)"]

[project.optional-dependencies]
console = ["pillow (>=11.1.0,<12.0.0)", "websockets (>=15.0.1,<16.0.0)"]
onebot_v11 = ["httpx (>=0.28.1,<0.29.0)", "websockets (>=15.0.1,<16.0.0)"]
qq = ["qq-botpy (>=1.2.1,<2.0.0)"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
clovers = { path = "D:/CLOVERS/clovers", develop = true }
clovers-apscheduler = { path = "D:/CLOVERS_PLUGINS/clovers-apscheduler", develop = true }
clovers-sarof = { path = "D:/CLOVERS_PLUGINS/clovers-sarof-project/test-package", develop = true }
scipy = "^1.15.1"
